### LA

In [ ]:
#Required PKGs

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

In [2]:
def eigendecomposition_demo():
    """
    Demonstrate eigendecomposition A = V * D * V^{-1}.

    For a square matrix A with n linearly independent eigenvectors,
    we can write A = V D V^{-1} where:
      - V columns are eigenvectors
      - D is diagonal with eigenvalues on the diagonal

    This diagonalization makes computing matrix powers and exponentials trivial:
      A^k = V D^k V^{-1}
    """
    print("=" * 60)
    print("SECTION 1: Eigendecomposition")
    print("=" * 60)

    # A symmetric matrix (guaranteed real eigenvalues, orthogonal eigenvectors)
    A = np.array([
        [4, 1, 2],
        [1, 3, 1],
        [2, 1, 5]
    ], dtype=float)

    print(f"\nMatrix A:\n{A}")

    # Compute eigendecomposition
    eigenvalues, V = np.linalg.eig(A)

    print(f"\nEigenvalues: {eigenvalues}")
    print(f"\nEigenvector matrix V:\n{V}")

    # Verify the decomposition: A = V * D * V^{-1}
    D = np.diag(eigenvalues)
    A_reconstructed = V @ D @ np.linalg.inv(V)
    print(f"\nReconstruction error ||A - V*D*V^(-1)||: {np.linalg.norm(A - A_reconstructed):.2e}")

    # For symmetric matrices, V is orthogonal so V^{-1} = V^T
    print(f"Orthogonality check ||V^T V - I||: {np.linalg.norm(V.T @ V - np.eye(3)):.2e}")

    # Compute A^5 using eigendecomposition (much more efficient than repeated multiplication)
    A_pow5_direct = np.linalg.matrix_power(A, 5)
    A_pow5_eig = V @ np.diag(eigenvalues**5) @ np.linalg.inv(V)
    print(f"||A^5 (direct) - A^5 (eigen)||: {np.linalg.norm(A_pow5_direct - A_pow5_eig):.2e}")

    return eigenvalues, V


In [3]:
eigendecomposition_demo()

SECTION 1: Eigendecomposition

Matrix A:
[[4. 1. 2.]
 [1. 3. 1.]
 [2. 1. 5.]]

Eigenvalues: [7.04891734 2.30797853 2.64310413]

Eigenvector matrix V:
[[ 0.59100905  0.73697623 -0.32798528]
 [ 0.32798528 -0.59100905 -0.73697623]
 [ 0.73697623 -0.32798528  0.59100905]]

Reconstruction error ||A - V*D*V^(-1)||: 6.57e-15
Orthogonality check ||V^T V - I||: 1.24e-15
||A^5 (direct) - A^5 (eigen)||: 7.95e-11


(array([7.04891734, 2.30797853, 2.64310413]),
 array([[ 0.59100905,  0.73697623, -0.32798528],
        [ 0.32798528, -0.59100905, -0.73697623],
        [ 0.73697623, -0.32798528,  0.59100905]]))